package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* lundi 30 avril 2012 12 h 02 CEST
*/

public interface HelloOperations 
{
  String sayHello ();

  // This line is an operation statement.
  String sayILoveYou (String name);
  void shutdown ();
} // interface HelloOperations
