/* This C header file is generated by NIT to compile modules and programs that requires ./chimie. */
#ifndef chimie_sep
#define chimie_sep
#include "general._sep.h"
#include <nit_common.h>

extern const classtable_elt_t VFT_chimie___Molecule[];

extern const classtable_elt_t VFT_chimie___Liaison[];

extern const classtable_elt_t VFT_chimie___Atome[];
extern const char LOCATE_chimie[];
extern const int SFT_chimie[];
#define ID_chimie___Molecule (SFT_chimie[0])
#define COLOR_chimie___Molecule (SFT_chimie[1])
#define INIT_TABLE_POS_chimie___Molecule (SFT_chimie[2] + 0)
#define CALL_chimie___Molecule___init(recv) ((chimie___Molecule___init_t)CALL((recv), (SFT_chimie[2] + 1)))
#define ID_chimie___Liaison (SFT_chimie[3])
#define COLOR_chimie___Liaison (SFT_chimie[4])
#define INIT_TABLE_POS_chimie___Liaison (SFT_chimie[5] + 0)
#define CALL_chimie___Liaison___init(recv) ((chimie___Liaison___init_t)CALL((recv), (SFT_chimie[5] + 1)))
#define ID_chimie___Atome (SFT_chimie[6])
#define COLOR_chimie___Atome (SFT_chimie[7])
#define INIT_TABLE_POS_chimie___Atome (SFT_chimie[8] + 0)
#define CALL_chimie___Atome___init(recv) ((chimie___Atome___init_t)CALL((recv), (SFT_chimie[8] + 1)))
static const char LOCATE_chimie___Molecule___init[];
void chimie___Molecule___init(val_t p0, int* init_table);
typedef void (*chimie___Molecule___init_t)(val_t p0, int* init_table);
val_t NEW_Molecule_chimie___Molecule___init();
static const char LOCATE_chimie___Liaison___init[];
void chimie___Liaison___init(val_t p0, int* init_table);
typedef void (*chimie___Liaison___init_t)(val_t p0, int* init_table);
val_t NEW_Liaison_chimie___Liaison___init();
static const char LOCATE_chimie___Atome___init[];
void chimie___Atome___init(val_t p0, int* init_table);
typedef void (*chimie___Atome___init_t)(val_t p0, int* init_table);
val_t NEW_Atome_chimie___Atome___init();
#endif
