/* This C header file is generated by NIT to compile modules and programs that requires ./general. */
#ifndef general_sep
#define general_sep
#include "standard._sep.h"
#include <nit_common.h>

extern const classtable_elt_t VFT_general___Graphe[];

extern const classtable_elt_t VFT_general___Aret[];

extern const classtable_elt_t VFT_general___Sommet[];
extern const char LOCATE_general[];
extern const int SFT_general[];
#define ID_general___Graphe (SFT_general[0])
#define COLOR_general___Graphe (SFT_general[1])
#define ATTR_general___Graphe_____atarets(recv) ATTR(recv, (SFT_general[2] + 0))
#define ATTR_general___Graphe_____atsommets(recv) ATTR(recv, (SFT_general[2] + 1))
#define INIT_TABLE_POS_general___Graphe (SFT_general[3] + 0)
#define VTID_general___Graphe___U(recv) (VAL2VFT(recv)[SFT_general[3] + 1].i)
#define VTCOLOR_general___Graphe___U(recv) (VAL2VFT(recv)[SFT_general[3] + 2].i)
#define VTID_general___Graphe___V(recv) (VAL2VFT(recv)[SFT_general[3] + 3].i)
#define VTCOLOR_general___Graphe___V(recv) (VAL2VFT(recv)[SFT_general[3] + 4].i)
#define CALL_general___Graphe___arets(recv) ((general___Graphe___arets_t)CALL((recv), (SFT_general[3] + 5)))
#define CALL_general___Graphe___arets__eq(recv) ((general___Graphe___arets__eq_t)CALL((recv), (SFT_general[3] + 6)))
#define CALL_general___Graphe___sommets(recv) ((general___Graphe___sommets_t)CALL((recv), (SFT_general[3] + 7)))
#define CALL_general___Graphe___sommets__eq(recv) ((general___Graphe___sommets__eq_t)CALL((recv), (SFT_general[3] + 8)))
#define CALL_general___Graphe___addSommet(recv) ((general___Graphe___addSommet_t)CALL((recv), (SFT_general[3] + 9)))
#define CALL_general___Graphe___addAret(recv) ((general___Graphe___addAret_t)CALL((recv), (SFT_general[3] + 10)))
#define CALL_general___Graphe___init(recv) ((general___Graphe___init_t)CALL((recv), (SFT_general[3] + 11)))
#define ID_general___Aret (SFT_general[4])
#define COLOR_general___Aret (SFT_general[5])
#define ATTR_general___Aret_____atgraphe(recv) ATTR(recv, (SFT_general[6] + 0))
#define ATTR_general___Aret_____atsommet1(recv) ATTR(recv, (SFT_general[6] + 1))
#define ATTR_general___Aret_____atsommet2(recv) ATTR(recv, (SFT_general[6] + 2))
#define INIT_TABLE_POS_general___Aret (SFT_general[7] + 0)
#define VTID_general___Aret___T(recv) (VAL2VFT(recv)[SFT_general[7] + 1].i)
#define VTCOLOR_general___Aret___T(recv) (VAL2VFT(recv)[SFT_general[7] + 2].i)
#define VTID_general___Aret___V(recv) (VAL2VFT(recv)[SFT_general[7] + 3].i)
#define VTCOLOR_general___Aret___V(recv) (VAL2VFT(recv)[SFT_general[7] + 4].i)
#define CALL_general___Aret___graphe(recv) ((general___Aret___graphe_t)CALL((recv), (SFT_general[7] + 5)))
#define CALL_general___Aret___graphe__eq(recv) ((general___Aret___graphe__eq_t)CALL((recv), (SFT_general[7] + 6)))
#define CALL_general___Aret___sommet1(recv) ((general___Aret___sommet1_t)CALL((recv), (SFT_general[7] + 7)))
#define CALL_general___Aret___sommet1__eq(recv) ((general___Aret___sommet1__eq_t)CALL((recv), (SFT_general[7] + 8)))
#define CALL_general___Aret___sommet2(recv) ((general___Aret___sommet2_t)CALL((recv), (SFT_general[7] + 9)))
#define CALL_general___Aret___sommet2__eq(recv) ((general___Aret___sommet2__eq_t)CALL((recv), (SFT_general[7] + 10)))
#define CALL_general___Aret___init(recv) ((general___Aret___init_t)CALL((recv), (SFT_general[7] + 11)))
#define CALL_general___Aret___addSommet(recv) ((general___Aret___addSommet_t)CALL((recv), (SFT_general[7] + 12)))
#define CALL_general___Aret___setGraphe(recv) ((general___Aret___setGraphe_t)CALL((recv), (SFT_general[7] + 13)))
#define CALL_general___Aret___isGrapheNull(recv) ((general___Aret___isGrapheNull_t)CALL((recv), (SFT_general[7] + 14)))
#define CALL_general___Aret___isEmpty(recv) ((general___Aret___isEmpty_t)CALL((recv), (SFT_general[7] + 15)))
#define ID_general___Sommet (SFT_general[8])
#define COLOR_general___Sommet (SFT_general[9])
#define ATTR_general___Sommet_____atarets(recv) ATTR(recv, (SFT_general[10] + 0))
#define ATTR_general___Sommet_____atgraphe(recv) ATTR(recv, (SFT_general[10] + 1))
#define INIT_TABLE_POS_general___Sommet (SFT_general[11] + 0)
#define VTID_general___Sommet___T(recv) (VAL2VFT(recv)[SFT_general[11] + 1].i)
#define VTCOLOR_general___Sommet___T(recv) (VAL2VFT(recv)[SFT_general[11] + 2].i)
#define VTID_general___Sommet___U(recv) (VAL2VFT(recv)[SFT_general[11] + 3].i)
#define VTCOLOR_general___Sommet___U(recv) (VAL2VFT(recv)[SFT_general[11] + 4].i)
#define CALL_general___Sommet___arets(recv) ((general___Sommet___arets_t)CALL((recv), (SFT_general[11] + 5)))
#define CALL_general___Sommet___arets__eq(recv) ((general___Sommet___arets__eq_t)CALL((recv), (SFT_general[11] + 6)))
#define CALL_general___Sommet___graphe(recv) ((general___Sommet___graphe_t)CALL((recv), (SFT_general[11] + 7)))
#define CALL_general___Sommet___graphe__eq(recv) ((general___Sommet___graphe__eq_t)CALL((recv), (SFT_general[11] + 8)))
#define CALL_general___Sommet___init(recv) ((general___Sommet___init_t)CALL((recv), (SFT_general[11] + 9)))
#define CALL_general___Sommet___addAret(recv) ((general___Sommet___addAret_t)CALL((recv), (SFT_general[11] + 10)))
#define CALL_general___Sommet___setGraphe(recv) ((general___Sommet___setGraphe_t)CALL((recv), (SFT_general[11] + 11)))
#define CALL_general___Sommet___isGrapheNull(recv) ((general___Sommet___isGrapheNull_t)CALL((recv), (SFT_general[11] + 12)))
static const char LOCATE_general___Graphe___arets[];
val_t general___Graphe___arets(val_t p0);
typedef val_t (*general___Graphe___arets_t)(val_t p0);
static const char LOCATE_general___Graphe___arets__eq[];
void general___Graphe___arets__eq(val_t p0, val_t p1);
typedef void (*general___Graphe___arets__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Graphe___sommets[];
val_t general___Graphe___sommets(val_t p0);
typedef val_t (*general___Graphe___sommets_t)(val_t p0);
static const char LOCATE_general___Graphe___sommets__eq[];
void general___Graphe___sommets__eq(val_t p0, val_t p1);
typedef void (*general___Graphe___sommets__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Graphe___addSommet[];
void general___Graphe___addSommet(val_t p0, val_t p1);
typedef void (*general___Graphe___addSommet_t)(val_t p0, val_t p1);
static const char LOCATE_general___Graphe___addAret[];
void general___Graphe___addAret(val_t p0, val_t p1);
typedef void (*general___Graphe___addAret_t)(val_t p0, val_t p1);
static const char LOCATE_general___Graphe___init[];
void general___Graphe___init(val_t p0, int* init_table);
typedef void (*general___Graphe___init_t)(val_t p0, int* init_table);
val_t NEW_Graphe_general___Graphe___init();
static const char LOCATE_general___Aret___graphe[];
val_t general___Aret___graphe(val_t p0);
typedef val_t (*general___Aret___graphe_t)(val_t p0);
static const char LOCATE_general___Aret___graphe__eq[];
void general___Aret___graphe__eq(val_t p0, val_t p1);
typedef void (*general___Aret___graphe__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Aret___sommet1[];
val_t general___Aret___sommet1(val_t p0);
typedef val_t (*general___Aret___sommet1_t)(val_t p0);
static const char LOCATE_general___Aret___sommet1__eq[];
void general___Aret___sommet1__eq(val_t p0, val_t p1);
typedef void (*general___Aret___sommet1__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Aret___sommet2[];
val_t general___Aret___sommet2(val_t p0);
typedef val_t (*general___Aret___sommet2_t)(val_t p0);
static const char LOCATE_general___Aret___sommet2__eq[];
void general___Aret___sommet2__eq(val_t p0, val_t p1);
typedef void (*general___Aret___sommet2__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Aret___init[];
void general___Aret___init(val_t p0, int* init_table);
typedef void (*general___Aret___init_t)(val_t p0, int* init_table);
val_t NEW_Aret_general___Aret___init();
static const char LOCATE_general___Aret___addSommet[];
void general___Aret___addSommet(val_t p0, val_t p1, val_t p2);
typedef void (*general___Aret___addSommet_t)(val_t p0, val_t p1, val_t p2);
static const char LOCATE_general___Aret___setGraphe[];
void general___Aret___setGraphe(val_t p0, val_t p1);
typedef void (*general___Aret___setGraphe_t)(val_t p0, val_t p1);
static const char LOCATE_general___Aret___isGrapheNull[];
val_t general___Aret___isGrapheNull(val_t p0);
typedef val_t (*general___Aret___isGrapheNull_t)(val_t p0);
static const char LOCATE_general___Aret___isEmpty[];
val_t general___Aret___isEmpty(val_t p0);
typedef val_t (*general___Aret___isEmpty_t)(val_t p0);
static const char LOCATE_general___Sommet___arets[];
val_t general___Sommet___arets(val_t p0);
typedef val_t (*general___Sommet___arets_t)(val_t p0);
static const char LOCATE_general___Sommet___arets__eq[];
void general___Sommet___arets__eq(val_t p0, val_t p1);
typedef void (*general___Sommet___arets__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Sommet___graphe[];
val_t general___Sommet___graphe(val_t p0);
typedef val_t (*general___Sommet___graphe_t)(val_t p0);
static const char LOCATE_general___Sommet___graphe__eq[];
void general___Sommet___graphe__eq(val_t p0, val_t p1);
typedef void (*general___Sommet___graphe__eq_t)(val_t p0, val_t p1);
static const char LOCATE_general___Sommet___init[];
void general___Sommet___init(val_t p0, int* init_table);
typedef void (*general___Sommet___init_t)(val_t p0, int* init_table);
val_t NEW_Sommet_general___Sommet___init();
static const char LOCATE_general___Sommet___addAret[];
void general___Sommet___addAret(val_t p0, val_t p1);
typedef void (*general___Sommet___addAret_t)(val_t p0, val_t p1);
static const char LOCATE_general___Sommet___setGraphe[];
void general___Sommet___setGraphe(val_t p0, val_t p1);
typedef void (*general___Sommet___setGraphe_t)(val_t p0, val_t p1);
static const char LOCATE_general___Sommet___isGrapheNull[];
val_t general___Sommet___isGrapheNull(val_t p0);
typedef val_t (*general___Sommet___isGrapheNull_t)(val_t p0);
#endif
