/* This C header file is generated by NIT to compile modules and programs that requires ./informatique. */
#ifndef informatique_sep
#define informatique_sep
#include "general._sep.h"
#include <nit_common.h>

extern const classtable_elt_t VFT_informatique___Reseau[];

extern const classtable_elt_t VFT_informatique___Cable[];

extern const classtable_elt_t VFT_informatique___Ordinateur[];
extern const char LOCATE_informatique[];
extern const int SFT_informatique[];
#define ID_informatique___Reseau (SFT_informatique[0])
#define COLOR_informatique___Reseau (SFT_informatique[1])
#define INIT_TABLE_POS_informatique___Reseau (SFT_informatique[2] + 0)
#define CALL_informatique___Reseau___init(recv) ((informatique___Reseau___init_t)CALL((recv), (SFT_informatique[2] + 1)))
#define ID_informatique___Cable (SFT_informatique[3])
#define COLOR_informatique___Cable (SFT_informatique[4])
#define INIT_TABLE_POS_informatique___Cable (SFT_informatique[5] + 0)
#define CALL_informatique___Cable___init(recv) ((informatique___Cable___init_t)CALL((recv), (SFT_informatique[5] + 1)))
#define ID_informatique___Ordinateur (SFT_informatique[6])
#define COLOR_informatique___Ordinateur (SFT_informatique[7])
#define INIT_TABLE_POS_informatique___Ordinateur (SFT_informatique[8] + 0)
#define CALL_informatique___Ordinateur___init(recv) ((informatique___Ordinateur___init_t)CALL((recv), (SFT_informatique[8] + 1)))
static const char LOCATE_informatique___Reseau___init[];
void informatique___Reseau___init(val_t p0, int* init_table);
typedef void (*informatique___Reseau___init_t)(val_t p0, int* init_table);
val_t NEW_Reseau_informatique___Reseau___init();
static const char LOCATE_informatique___Cable___init[];
void informatique___Cable___init(val_t p0, int* init_table);
typedef void (*informatique___Cable___init_t)(val_t p0, int* init_table);
val_t NEW_Cable_informatique___Cable___init();
static const char LOCATE_informatique___Ordinateur___init[];
void informatique___Ordinateur___init(val_t p0, int* init_table);
typedef void (*informatique___Ordinateur___init_t)(val_t p0, int* init_table);
val_t NEW_Ordinateur_informatique___Ordinateur___init();
#endif
