/* This C header file is generated by NIT to compile modules and programs that requires ./test. */
#ifndef test_sep
#define test_sep
#include "chimie._sep.h"
#include "informatique._sep.h"
#include <nit_common.h>
extern const char LOCATE_test[];
extern const int SFT_test[];
static const char LOCATE_test___Sys___main[];
void test___Sys___main(val_t p0);
typedef void (*test___Sys___main_t)(val_t p0);
val_t NEW_Sys_standard___kernel___Sys___init();
#endif
